name: seekhelper_assignment
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  http: ^1.1.0
  go_router: ^12.1.3
  equatable: ^2.0.5
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
